### ISSUE TITLE
Faire une bibliothèque python/brassage ?

### ISSUE THREAD

**Issue by glibersat** [314r/joliebulle#104]
Hello,

Tout d'abord, merci pour l'initiative joliebulle ! :)
Concernant les différents calculs qui sont dans joliebulle, avez-vous pensé ou seriez-vous partants pour les externaliser dans une bibliothèque python dédiée au brassage ? J'y pense car j'ai besoin de tout ceci pour un logiciel et si je peux éviter de repartir de zéro, c'est toujours mieux !

Merci,

Guillaume

**Comment by dzen** [comment]
C'est effectivement une très bonne idée ! 
Cette bibliothèque pourrait aider à rendre le code robuste et clair, avec une suite de tests !

**Comment by glibersat** [comment]
Cool ! Et oui, totalement d'accord pour la suite de tests... surtout sur ces calculs qui sont tout de même pas évidents à mettre bout à bout, une petite erreur peut vite mener à une longue recherche :)

Je commence à regarder ça la semaine prochaine alors, merci

**Comment by 314r** [comment]
Salut la compagnie.
C'est une très bonne idée, mais ce n'est pas moi qui vais la mettre en œuvre. Dans la prochaine version, il n'y aura quasiment plus aucun calcul réalisé en python, je fais la bascule vers du javascript. Ce qui reste de python/pyqt servira surtout à gérer le système de fichiers.
