### ISSUE TITLE
bug en mode brassage lors de la création d'une nouvelle recette

### ISSUE THREAD

**Issue by artiche** [314r/joliebulle#106]
Bonjour,

dans la dernière version (3.5), j'ai le bug suivant :

je crée une nouvelle recette, j'ajoute les ingrédients, je choisis un mode de brassage de type "infusion".
j'enregistre, puis je clique immédiatement sur le bouton pour passer en mode brassage.

Et là, à peu près tous les calculs sont vides (eau ajoutée, température eau, volue d'eau de tinçage, volume de grain... etc) voir capture d'écran.

![image](https://cloud.githubusercontent.com/assets/500075/14791178/eacc7ce2-0b14-11e6-9068-07e62262548b.png)

Si on quitte le logiciel, qu'on le relance et qu'on réouvre la recette, les calculs sont bien là.

**Comment by 314r** [comment]
Ok, merci pour ce retour. Je me penche sur le sujet dès que je peux.
