### ISSUE TITLE
plantage en sortie de joliebulle (version windows)

### ISSUE THREAD

**Issue by artiche** [314r/joliebulle#107]
quand on crée  ou on supprime une recette, une exception est levée en sortie du logiciel, ce qui donne l'écran d'erreur suivant sous windows : 

![image](https://cloud.githubusercontent.com/assets/500075/14791330/bb562854-0b15-11e6-8c25-e3c3e50bbe78.png)

en regardant l'erreur avec visual studio, on voit qu'il s'agit d'une erreur dans la dll QtGui4.dll : 

![image](https://cloud.githubusercontent.com/assets/500075/14791402/04eee51e-0b16-11e6-8ef2-c8004bacdc24.png)

**Comment by 314r** [comment]
Merci.
J'arrive à reproduire le bug chez moi, mais de façon inconstante.
Ma courte expérience de ce genre de bug sous windows tend à me faire penser que je vais bien galérer...

**Comment by 314r** [comment]
Je pense que le commit 935 résout le problème. Je laisse le bug ouvert en attendant de tester un peu plus.
