### ISSUE TITLE
Probème install joliebulle 3.6 sur fedora 24

### ISSUE THREAD

**Issue by jbarascut** [314r/joliebulle#122]
Bonjour,

Je rencontre un problème d'installation de joliebulle sur la version 24 de fedora.

[gnupyx@localhost ~]$ sudo dnf config-manager --add-repo http://download.opensuse.org/repositories/home:314r/Fedora_24/home:314r.repo
[sudo] Mot de passe de gnupyx : 
Ajout du dépôt depuis : http://download.opensuse.org/repositories/home:314r/Fedora_24/home:314r.repo
[gnupyx@localhost ~]$ sudo dnf install joliebulle
JolieBulle (Fedora_24)                           16 kB/s | 2.7 kB     00:00    
Fedora 24 - x86_64 - Updates                    4.5 MB/s |  13 MB     00:02    
Vérification de l'expiration des métadonnées effectuée il y a 0:00:06 sur Sun Jul 31 12:02:49 2016.
Dépendances résolues.
================================================================================
 Package                      Architecture
                                        Version              Dépôt        Taille
================================================================================
Installation de:
 joliebulle                   noarch    3.6.0-72.1           home_314r    853 k
 openal-soft                  x86_64    1.17.2-2.fc24        fedora       337 k
 python-qt5-rpm-macros        noarch    5.6-4.fc24           updates       13 k
 python3-qt5                  x86_64    5.6-4.fc24           updates      4.0 M
 python3-sip                  x86_64    4.18-2.fc24          updates      126 k
 qt5-qtconnectivity           x86_64    5.6.1-2.fc24         updates      399 k
 qt5-qtenginio                x86_64    1:1.6.1-2.fc24       updates      173 k
 qt5-qtmultimedia             x86_64    5.6.1-3.fc24         updates      789 k
 qt5-qtserialport             x86_64    5.6.1-1.fc24         updates       66 k
 qt5-qtsvg                    x86_64    5.6.1-2.fc24         updates      158 k
 qt5-qttools-common           noarch    5.6.1-2.fc24         updates       25 k
 qt5-qttools-libs-clucene     x86_64    5.6.1-2.fc24         updates       50 k
 qt5-qttools-libs-designer    x86_64    5.6.1-2.fc24         updates      2.7 M
 qt5-qttools-libs-help        x86_64    5.6.1-2.fc24         updates      219 k
 qt5-qtwebsockets             x86_64    5.6.1-2.fc24         updates       82 k

Résumé de la transaction
================================================================================
Installation  15 Paquets

Taille totale des téléchargements : 9.9 M
Taille d'installation : 38 M
Est-ce correct [o/N] : o
Téléchargement des paquets :
(1/15): python-qt5-rpm-macros-5.6-4.fc24.noarch  78 kB/s |  13 kB     00:00    
(2/15): joliebulle-3.6.0-72.1.noarch.rpm        1.0 MB/s | 853 kB     00:00    
(3/15): qt5-qtmultimedia-5.6.1-3.fc24.x86_64.rp 1.1 MB/s | 789 kB     00:00    
(4/15): qt5-qtserialport-5.6.1-1.fc24.x86_64.rp 329 kB/s |  66 kB     00:00    
(5/15): qt5-qtwebsockets-5.6.1-2.fc24.x86_64.rp 335 kB/s |  82 kB     00:00    
(6/15): qt5-qtsvg-5.6.1-2.fc24.x86_64.rpm       356 kB/s | 158 kB     00:00    
(7/15): python3-qt5-5.6-4.fc24.x86_64.rpm       2.9 MB/s | 4.0 MB     00:01    
(8/15): python3-sip-4.18-2.fc24.x86_64.rpm      850 kB/s | 126 kB     00:00    
(9/15): qt5-qtenginio-1.6.1-2.fc24.x86_64.rpm   1.1 MB/s | 173 kB     00:00    
(10/15): openal-soft-1.17.2-2.fc24.x86_64.rpm   849 kB/s | 337 kB     00:00    
(11/15): qt5-qtconnectivity-5.6.1-2.fc24.x86_64 1.2 MB/s | 399 kB     00:00    
(12/15): qt5-qttools-common-5.6.1-2.fc24.noarch 451 kB/s |  25 kB     00:00    
(13/15): qt5-qttools-libs-clucene-5.6.1-2.fc24. 408 kB/s |  50 kB     00:00    
(14/15): qt5-qttools-libs-help-5.6.1-2.fc24.x86 1.0 MB/s | 219 kB     00:00    
(15/15): qt5-qttools-libs-designer-5.6.1-2.fc24 3.5 MB/s | 2.7 MB     00:00    
--------------------------------------------------------------------------------
Total                                           1.8 MB/s | 9.9 MB     00:05     
attention : /var/cache/dnf/home_314r-3ff27b86f65903ae/packages/joliebulle-3.6.0-72.1.noarch.rpm: Entête V3 RSA/SHA256 Signature, clé ID d3af04ca: NOKEY
Importation de la clé GPG 0xD3AF04CA :
Utilisateur : « home:314r OBS Project <home:314r@build.opensuse.org> »
Empreinte : EDA3 8C5B F92E 021F 7DE1 CBD2 1133 457E D3AF 04CA
Provenance : http://download.opensuse.org/repositories/home:/314r/Fedora_24//repodata/repomd.xml.key
Est-ce correct [o/N] : o
La clé a été importée avec succès
Test de la transaction en cours
La vérification de la transaction a réussi.
Lancement de la transaction de test
Transaction de test réussie.
Exécution de la transaction
  Installation de               : qt5-qttools-common-5.6.1-2.fc24.noarc    1/15 
  Installation de               : qt5-qttools-libs-designer-5.6.1-2.fc2    2/15 
  Installation de               : qt5-qttools-libs-clucene-5.6.1-2.fc24    3/15 
  Installation de               : qt5-qttools-libs-help-5.6.1-2.fc24.x8    4/15 
  Installation de               : qt5-qtenginio-1:1.6.1-2.fc24.x86_64      5/15 
  Installation de               : qt5-qtconnectivity-5.6.1-2.fc24.x86_6    6/15 
  Installation de               : python3-sip-4.18-2.fc24.x86_64           7/15 
  Installation de               : openal-soft-1.17.2-2.fc24.x86_64         8/15 
  Installation de               : qt5-qtmultimedia-5.6.1-3.fc24.x86_64     9/15 
  Installation de               : qt5-qtwebsockets-5.6.1-2.fc24.x86_64    10/15 
  Installation de               : qt5-qtsvg-5.6.1-2.fc24.x86_64           11/15 
  Installation de               : qt5-qtserialport-5.6.1-1.fc24.x86_64    12/15 
  Installation de               : python-qt5-rpm-macros-5.6-4.fc24.noar   13/15 
  Installation de               : python3-qt5-5.6-4.fc24.x86_64           14/15 
  Installation de               : joliebulle-3.6.0-72.1.noarch            15/15 
  Vérification                  : joliebulle-3.6.0-72.1.noarch             1/15 
  Vérification                  : python3-qt5-5.6-4.fc24.x86_64            2/15 
  Vérification                  : python-qt5-rpm-macros-5.6-4.fc24.noar    3/15 
  Vérification                  : qt5-qtmultimedia-5.6.1-3.fc24.x86_64     4/15 
  Vérification                  : qt5-qtserialport-5.6.1-1.fc24.x86_64     5/15 
  Vérification                  : qt5-qtsvg-5.6.1-2.fc24.x86_64            6/15 
  Vérification                  : qt5-qtwebsockets-5.6.1-2.fc24.x86_64     7/15 
  Vérification                  : openal-soft-1.17.2-2.fc24.x86_64         8/15 
  Vérification                  : python3-sip-4.18-2.fc24.x86_64           9/15 
  Vérification                  : qt5-qtconnectivity-5.6.1-2.fc24.x86_6   10/15 
  Vérification                  : qt5-qtenginio-1:1.6.1-2.fc24.x86_64     11/15 
  Vérification                  : qt5-qttools-libs-designer-5.6.1-2.fc2   12/15 
  Vérification                  : qt5-qttools-common-5.6.1-2.fc24.noarc   13/15 
  Vérification                  : qt5-qttools-libs-help-5.6.1-2.fc24.x8   14/15 
  Vérification                  : qt5-qttools-libs-clucene-5.6.1-2.fc24   15/15 

Installé:
  joliebulle.noarch 3.6.0-72.1                                                  
  openal-soft.x86_64 1.17.2-2.fc24                                              
  python-qt5-rpm-macros.noarch 5.6-4.fc24                                       
  python3-qt5.x86_64 5.6-4.fc24                                                 
  python3-sip.x86_64 4.18-2.fc24                                                
  qt5-qtconnectivity.x86_64 5.6.1-2.fc24                                        
  qt5-qtenginio.x86_64 1:1.6.1-2.fc24                                           
  qt5-qtmultimedia.x86_64 5.6.1-3.fc24                                          
  qt5-qtserialport.x86_64 5.6.1-1.fc24                                          
  qt5-qtsvg.x86_64 5.6.1-2.fc24                                                 
  qt5-qttools-common.noarch 5.6.1-2.fc24                                        
  qt5-qttools-libs-clucene.x86_64 5.6.1-2.fc24                                  
  qt5-qttools-libs-designer.x86_64 5.6.1-2.fc24                                 
  qt5-qttools-libs-help.x86_64 5.6.1-2.fc24                                     
  qt5-qtwebsockets.x86_64 5.6.1-2.fc24                                          

Terminé !

L'installation c'est correctement déroulé.

Quand je lance joliebulle j'ai un problème de dépendance.

[gnupyx@localhost ~]$ joliebulle 
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    from PyQt5 import QtWebKit
ImportError: cannot import name 'QtWebKit'

Qu'elle est la dépendance manquante ou la ligne d'import à modifier?

**Comment by 314r** [comment]
La dépendance manquante est le paquet python3-qt5-webkit. 
Le problème est résolu.
Merci pour le retour !
