### ISSUE TITLE
Problème d'encodage de "<=>" dans la zone Notes de la recette

### ISSUE THREAD

**Issue by cedricTutzo** [314r/joliebulle#128]
Bonjour,

En clonant une recette d'une ancienne version de Joliebulle j'ai dupliqué l'équivalent mathématique ( <=> ).
L'enregistrement s'est bien passé mais en relancant l'application, la recette n'était pas visible.

En regardant le fichier XML de la recette et en comparant le clone avec l'original, j'ai vu que dans la précédente version il y avait un encodage HTML qui transformait cette chaine en "&lt;=&gt;".
En reproduisant cette modification à la main dans le fichier XML, l'application est capable de charger la recette.
En revanche à l'enregistrement on perd l'encodage et la recette n'est plus visible à la réouverture de l'application.

Merci pour votre travail.

Version Jolie bulle : 3.6
OS : Linux Mint 18.1

**Comment by cedricTutzo** [comment]
Arfff Sacré HTML...

Bon je reprends une phrase qui a été interpretée.

> En regardant le fichier XML de la recette et en comparant le clone avec l'original, j'ai vu que dans la précédente version il y avait un encodage HTML qui transformait cette chaine en **" & l t ; = & g t ; "**.

(sans les espaces entre les caractères. ;) )

**Comment by flagos** [comment]
This bug is somehow a duplicate of #126 . I made a pull request that can fix both. https://github.com/314r/joliebulle/pull/132

Cheers

**Comment by 314r** [comment]
Fixed.
