### ISSUE TITLE
Recettes inaccessibles

### ISSUE THREAD

**Issue by tomarcello** [314r/joliebulle#133]
Bonjour, 
Mes recettes n'apparaissent plus dans le logiciel alors qu'elles sont bien dans le dossier .Config. Plus gênant encore, le bouton "créer une nouvelle recette" ne fait rien.  je suis sous Ubuntu 16.10 et mon joliebulle est une 3.6 installée depuis le lien du site "Ubuntu, fedora, openSUSE"  (.deb).
Plus étrange encore,  j'ai un copain qui m'a montré exactement le même bug sous Windows.

**Comment by flagos** [comment]
Salut,

C'est certainement un duplicate de #128 ou de #126 pour lesquels un correctif est en cours. 

Je t'invite à éditer tes recettes présentes dans ton dossier .config et à regarder si tu n'as pas un caractère particulier dans tes recettes comme &, < ou > , notamment dans entre les balises notes.

**Comment by 314r** [comment]
On peut penser que le problème vient de la dernière recette créée ou éditée, commence par là.
Sinon, n'hésite pas à m'envoyer le fichier qui pose problème ou même tout ton dossier de recettes pour que j'y jette un oeil directement.

**Comment by tomarcello** [comment]
De retour du ski, j'ai jeté un coup d'œil à mes recettes, j'ai identifiée
celle qui plante. J'ai viré les signes spéciaux (mais j'en ai peut être
loupé). Tu peux voir le fichier joint. Encore merci pour ce super programme.

**Comment by 314r** [comment]
Fixed.
