### ISSUE TITLE
Add entry to journal not working

### ISSUE THREAD

**Issue by j0ack** [314r/joliebulle#141]
Version 3.6, debian buster

Adding an entry directly to the journal from a recipe is not working.

**Comment by 314r** [comment]
Ok.
Not reproducible under KDE Neon and Xubuntu 17.04.

**Comment by 314r** [comment]
Is your problem solved ?

**Comment by j0ack** [comment]
I didn't find a way to reproduce this, there was definitely an issue here but seems to be in special conditions
