### ISSUE TITLE
Impossible de modifier une recette.

### ISSUE THREAD

**Issue by alex38260** [314r/joliebulle#144]
J'ai installé joliebulle 3.7.01 sur mes deux pc ( sous debian stable) et sur l'un, depuis quelques jours je ne peux plus modifier une recette. Quand j'appuie sur enregistrer rien ne se passe. 
 J'ai essayé de réinstaller le logiciel de supprimer les fichiers de configuration,  les recettes, toujours le même problème...
Merci

**Comment by 314r** [comment]
Ok, le problème se pose avec une seule recette en particulier, ou c'est un problème général ?

**Comment by alex38260** [comment]
Bonjour,

le problème se pose sur les recettes que j'ai crées depuis la mise à jour vers la 3.7, je viens de créer une nouvelle recette. SI je ferme jolie bulle et que j'essaie de nouveau de la modifier je ne peux plus enregistrer les modifs. Alors que les recettes crées avec la versions 3.6 sont encore modifiables.

Je n'ai pas ce problème  avec l'autre PC aussi sous debian 9.

Merci pour ce soft vraiment pratique, agréable à utiliser et précis!


________________________________
De : 314r <notifications@github.com>
Envoyé : lundi 30 octobre 2017 20:44
À : 314r/joliebulle
Cc : alex38260; Author
Objet : Re: [314r/joliebulle] Impossible de modifier une recette. (#144)


Ok, le problème se pose avec une seule recette en particulier, ou c'est un problème général ?

**Comment by 314r** [comment]
J'arrive à reproduire le bug.
Il s'agit d'un problème critique qui devrait affecter tous les utilisateurs.
Je corrige, et je réempaquete une nouvelle version.

**Comment by 314r** [comment]
En tout cas, merci beaucoup pour ce retour.
C'est utile pour tout le monde, et c'est ce qui permet au logiciel de progresser !
Une 3.7.1 est dans les tuyaux.
