### ISSUE TITLE
Problème d'encodage dans les houblons

### ISSUE THREAD

**Issue by GaetanNaulin** [314r/joliebulle#145]
Bonjour,
Je rencontre un problème d'encodage avec les houblons sur la version 3.6 sous Windows 10.
Quand on veut ajouter un houblon dans sa recette, le Brewer's Gold affiche `&#39;` à la place de l'apostrophe. C'est pareil une fois ajouté à la recette.
Par contre dans la base d'édition des ingrédients, il n'y a pas le problème.

Après test, c'est pareil si l'on ajoute un apostrophe à un malt dans la base d'ingrédient.

**Comment by 314r** [comment]
Confirmé sous 3.7.
Je vais y jeter un oeil.
Merci !
