### ISSUE TITLE
Problème d'enregistrement des notes

### ISSUE THREAD

**Issue by sn0oz** [314r/joliebulle#146]
Salut, avec la version 3.7.1 sous Ubuntu, les notes de la recettes sont enregistrées dans le fichier mais sans la balise NOTES, ce qui empêche l'affichage lors de la réouverture.

**Comment by 314r** [comment]
Bonjour,
Oui bug confirmé, et corrigé.
C'est moche.
Merci pour le retour !

**Comment by sn0oz** [comment]
Merci pour la correction rapide.
