### ISSUE TITLE
nom de fichier recette

### ISSUE THREAD

**Issue by sn0oz** [314r/joliebulle#147]
En version 3.7.1 sous Ubuntu lors de la création d'une recette, le fichier enregistré est nommé par un chiffre qui semble correspondre à un timestamp. Par exemple, un fichier créé le 20/11/2017 à 13h12 est nommé 15111799537.xml (1511179953 étant le unix correspondant à l'heure d'enregistrement).

**Comment by 314r** [comment]
Exactement.
C'est fait pour.
