### ISSUE TITLE
Le futur de Joliebulle

### ISSUE THREAD

**Issue by Superpat** [314r/joliebulle#150]
Salut! Apres discussions avec Nico sur mastodon j'ai decider de venir jeter un coup d'oeil a Joliebulle. Je n'ai pas encore eu le temps d'essayer le projet sur une de mes machines, mais je ferais ca bientot.

https://mastodon.beerfactory.org/@nico/99735541727664666

J'ouvre ce issue pour discuter des questions ouvertes sur le dev futur de joliebulle. Quelles questions et discussions reste t-il a avoir? Quels sont les requirements? Le dev se fait en anglais francais ou un melange? Bref, j'ai hate d'en discuter!

**Comment by 314r** [comment]
Bonjour et bienvenue à bord !
Je t'invite à jeter un oeil ici : https://github.com/314r/joliebulle/pull/117
et ici : https://riot.im/app/#/room/#joliebulle:matrix.org
pour avoir une vision un peu générale de ce qui a été discuté.

Historiquement joliebulle était initialement en français, puis plus ou moins traduit en anglais, mais la nouvelle base sera en anglais.
Pour le moment, je m'oriente vers une solution à base de Electron + React. L'avenir est très ouvert, donc il n'y a pas vraiment de question en suspens. Il faut juste se mettre au travail.
Mon souhait est de produire un logiciel de bureau à mon rythme, tranquillou. Nicolas, qui suit le projet depuis plusieurs années a une vision un peu plus large avec son projet Beerfactory, et je crois qu'il s'oriente franchement vers une solution pur web.
