### ISSUE TITLE
Error opening /usr/share/joliebulle/static/html/toto: No such file or directory

### ISSUE THREAD

**Issue by shtrom** [314r/joliebulle#157]
Depuis la version 3.7.3 (-2 sur ArchLinux), ainsi que depuis le dépôt, j'ai cette erreur quand je veux visualiser une recette.
![Screenshot from 2019-06-22 15-11-05](https://user-images.githubusercontent.com/160280/59959713-f9cc5500-94ff-11e9-8dc1-7eceaf14ebb1.png)

Cela semble venir de là [0], mais ça ne semble pas avoir changé récemment.

J'ai aussi tenté de vider mon répertoire de recettes, mais la même chose arrive avec toutes les recettes d'exemple.

[0] https://github.com/314r/joliebulle/blob/f16218ebbe4cfa6c05a388e17f473f8def0e95ea/joliebulle/static/html/lib.html#L51

**Comment by shtrom** [comment]
Même problème avec 3.7 \:

Peut-être un problème avec les dépendences?

Dependences:
*  python: 3.7.3-1
* python-pyqt5: 5.12.2-1
* qt5-webkit: 5.212.0alpha2+156+g95401fe3908-3

**Comment by 314r** [comment]
Bonjour,

La branche 3.7 n'est plus maintenue.
Je me concentre maintenant sur Joliebulle 4.

A+
