### ISSUE TITLE
Refactoring main.py

### ISSUE THREAD

**Issue by njouanin** [314r/joliebulle#25]
Le fichier main.py devrait faire l'objet d'un "refactoring" afin de placer dans des fichiers différents ce qui est spécifique à chaque écran. Actuellement tout le code concernant l'écran de sélection des recettes, l'écran d'édition et l'écran de gestion des profils sont dans le même fichier .py. Ca serait plus facile à maintenir si chaque écran faisait l'objet d'un fichier (d'une classe) dédiée.

**Comment by 314r** [comment]
Je ferme. Le code python restant est voué a être de plus en plus limité à l'avenir, un refactoring n'a plus vraiment de sens.
