### ISSUE TITLE
Affichage volume eau pour empatage

### ISSUE THREAD

**Issue by Fbrachere** [314r/joliebulle#92]
Dans l'affichage en mode brassage, le volume d'eau pour l'empatage n'est pas indiqué.
En regardant le code source il semblerait que ce volume soit de 3 fois le poids de grains. (ratio de 3 litres par kg).
Il me semble que l'information est essentielle, au début je croyais que le volume nécessaire correspondait à "volume de maische à l'empatage soustrait de volume de grains", ce qui me  conduisait à faire une maische très épaisse. Mais en fait le volume de grains est une volume de grains mouillés donc il manquait d'eau à mon empatage.
Il serait aussi souhaitable que l'on puisse régler le ratio soit de manière globale, soit par recette, soit par profils de brassage.

**Comment by 314r** [comment]
Alors si, normalement le mode brassage indique le volume d'eau pour l'empâtage commepour le reste des paliers, et le ratio est ajustable.

Tu devrais avoir un truc qui ressemble à ça :

![jb](https://cloud.githubusercontent.com/assets/3924965/5606616/47a81742-9437-11e4-982d-636f2f14b780.png)

Ce n'est pas le cas ?

**Comment by Fbrachere** [comment]
Non, j'ai ça :
![capture d ecran de 2015-01-04 18 45 52](https://cloud.githubusercontent.com/assets/10390464/5606823/21802b6c-9442-11e4-8dbf-12ea383a8ac4.png)

**Comment by 314r** [comment]
Oui là il y a vraiment un souci. Tu peux m'envoyer le fichier de la recette par mail ?

**Comment by 314r** [comment]
Ok ok je vois le problème.
Ton premier palier est un palier de type température (chauffe directe),  alors qu'il devrait être de type infusion. Revois ton profil de brassage. Pour tous les paliers où tu ajoutes de l'eau chaude, c'est une infusion.

**Comment by Fbrachere** [comment]
Oui, je viens de m'en apercevoir aussi. Effectivement en changeant de type de palier on retrouve le volume d'eau et le ratio.
Donc mea culpa, mais je dirais pour ma défense que ce n'est pas évident au premier abord.
En tout cas félicitations pour le boulot accompli et le tout sous licence libre.

**Comment by 314r** [comment]
Effectivement ce n'est pas forcément très clair, il y a probablement des choses à améliorer de ce point de vue.

**Comment by 314r** [comment]
Dans la prochaine version, il y aura un rappel des types de paliers lors de la création d'un nouveau profil. Je ferme.
