### ISSUE TITLE
Clonage recette

### ISSUE THREAD

**Issue by sn0oz** [314r/joliebulle#99]
Une fonction de "clonage" d'une recette serait bien pratique, dans le cas où on veut modifier quelques paramètres mais aussi garder l'original d'une recette.
Pour l'instant je vais dans le répertoire des recettes, copie le fichier sous un autre nom et modifie le paramètre <NAME> dans le XML. Ca fonctionne mais ça n'est pas très pratique.

**Comment by 314r** [comment]
Très bonne idée. C'est une fonctionnalité qui a été réclamée de longue date, puis oubliée.
